name: A_B_tests
channels:
  - defaults
dependencies:
  - python=3.11
  - pytest
  - matplotlib
  - numpy
  - tk
  - pandas
  - pip
  - pip:
      - flake8==7.3.0
      - pydocstyle==6.3.0
      - ruff==0.15.17
